### ISSUE TITLE
Add setAttribute command for the profile module

### ISSUE THREAD

**Issue by reyraa** [Muzikie/blockchain#100]
### Description

As a step towards #95 , add a command to update the attributes of an existing user NFT.  Since we already have another command for transferring the ownership of the NFT token, this command should not perform the transfer action, meaning, we should not be able to change the `creatorAccount` using `setAttribute`.

### Acceptance Criteria

- Throw an error if not the owner
- Throw an error if NFT doesn't exist
- Do not allow transfers
- Add required unit tests

**Comment by haghighatcs** [comment]
This is already resolved by #122
